source "https://rubygems.org"

gem "rails", "4.1.4"
gem "sqlite3"
gem "sass-rails", "~> 4.0.3"
gem "uglifier", ">= 1.3.0"
gem "jquery-rails"
gem "spring", group: :development

gem "magic_lamp"
gem "teaspoon"
