source "https://rubygems.org"

gem "rails", "4.1.5"
gem "sqlite3"
gem "sass-rails", "~> 4.0.3"
gem "uglifier", ">= 1.3.0"
gem "jquery-rails"

gem "teaspoon", "0.8.0"
gem "magic_lamp", "1.1.0"
gem "database_cleaner"
gem "devise"

gem "pry"
gem "pry-nav"
gem "pry-doc"
