source "https://rubygems.org"

gem "rails", "4.1.1"
gem "sqlite3"
gem "sass-rails", "~> 4.0.3"
gem "uglifier", ">= 1.3.0"
gem "jquery-rails"

group :development, :test do
  gem "teaspoon"
  gem "magic_lamp"

  gem "spring"
  gem "pry"
  gem "pry-nav"
  gem "pry-debugger"
end
